baseURL = 'https://youkre.github.io/'
locale = 'zh-cn'
title = '优克'

theme = 'PaperMod'
enableRobotsTXT = true
hasCJKLanguage = true
timeZone = 'Asia/Shanghai'

[menus]
    [[menus.main]]
        name = 'Blog'
        url = '/unlost-sparks/'
        weight = 1
    [[menus.main]]
        name = '自然语言处理导论'
        url = '/slp3/'
        weight = 2

    [[menus.main]]
        name = 'PyTorch NLP 入门'
        url = '/nlp-getting-started/'
        weight = 3

[markup]
    [markup.goldmark]
        [markup.goldmark.parser]
            wrapStandAloneImageWithinParagraph = false
            [markup.goldmark.parser.attribute]
                block = true
                title = true
        [markup.goldmark.renderer]
            unsafe = true
        [markup.goldmark.extensions]
            [markup.goldmark.extensions.passthrough]
                enable = true
                [markup.goldmark.extensions.passthrough.delimiters]
                    inline = [['$', '$'], ['\(', '\)']]
                    block = [['\[', '\]'], ['$$', '$$']]

[params]
    ShowShareButtons = true
    ShowPostNavLinks = true
    ShowCodeCopyButtons = true
    # ShowRssButtonInSectionTermList = true
    [params.assets]
        favicon = "/favicon.ico"
    [params.label]
        icon = "/logo.png"

    [params.homeInfoParams]
        Title = "Unlost Sparks"
        Content = "工程中的灵光一现 → 精巧实现 → 无人知晓 → 自己遗忘”的循环，几乎是每个认真思考的工程师都会经历的隐性知识流失。\n\n写下来，就是对抗遗忘、积累智慧的最有效方式。"

    [[params.socialIcons]]
        name = 'rss'
        url = '/index.xml'
    [[params.socialIcons]]
        name = 'github'
        url = 'https://github.com/neefrankie'
        


[caches]
    [caches.images]
        dir = ':cacheDir/images'